### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by liutingfenga** [alltheblue/docs#5]
系统版本：Windows 11 专业版 21H2 
问题：
安装 eTest-Web-Setup-1.1.17.exe 安装成功后打开提示：
![Uploading 微信图片_20230605100723.png…]()
![Uploading 微信图片_20230605100728.png…]()

**Comment by liutingfenga** [comment]
[![pCCKLse.png](https://s1.ax1x.com/2023/06/05/pCCKLse.png)](https://imgse.com/i/pCCKLse)
[![pCCKqMD.png](https://s1.ax1x.com/2023/06/05/pCCKqMD.png)](https://imgse.com/i/pCCKqMD)

**Comment by xflihaibo** [comment]
收到反馈，我们尽快修复

**Comment by xflihaibo** [comment]
windonws 版本更新请下载试试：https://github.com/alltheblue/docs/releases/tag/eTest_v_1.1.18
