### ISSUE TITLE
chrome插件启动录制后，会导致输入框中选中的文本失焦

### ISSUE THREAD

**Issue by ss368829** [alltheblue/docs#8]
启动录制，会导致输入框中选中的文本失焦，关闭录制，选中的文本框才能正常输入。
![无法多选](https://github.com/alltheblue/docs/assets/105182004/a0d9d974-b527-4299-ada6-da15e2789cf7)

**Comment by xflihaibo** [comment]
选中文本是为了做断言处理，你选择输入文本需要做什么操作吗？
